### ISSUE TITLE
Feature Request: Hold the update untill the video player has been closed or start playing the next video file

### ISSUE THREAD

**Issue by CypherNL** [po5/player-tracker#3]
When playing a video file, the tracker updates all the services when the file plays. This is around 1 to 30 seconds after starting the video.

While this could work for some, i would like to have the updates being pushed out to the services when the video player closes or when the player switches to the next video file like you can set up in Taiga.

This would mean that the update times are on when you've completed an episode or movie instead of beginning it.

If this can be realised, maybe it's better to make this a toggle so the user can decide when the updates are being pushed out.

**Comment by po5** [comment]
With the current detection method, which I want to keep as simple as possible, it's not possible to detect the video progress.
I like the idea of waiting for the next file, I will look into it.
I had planned to wait for a file to be present for three consecutive 30 second checks before updating lists, would that be enough?

**Comment by CypherNL** [comment]
I don't need it to to track the video progress. Just holding off the update until the video file changes or the player closes is enough if it could be implemented with not much complexity.

The alternative is also good if those 30 second intervals can be changed since i would like it to be updated about more than a half than an episode length (13 minutes or something). But i do prefer holding it off until i've fully watched an episode or movie.

**Comment by po5** [comment]
How's 914998e?

**Comment by CypherNL** [comment]
It does seem to work so far. However It does update the next episode if that episode is played for a few seconds. (for example: You're late to close the program after watching an episode and it switches to the next one).

So an extra check for 3 30 seconds intervals would be preferred to avoid accidental updates.

**Comment by po5** [comment]
Implemented in 6492ba8, anything else?

**Comment by CypherNL** [comment]
Tested it and it works flawlessly.

The only thing i think would be nice if the tracker says that the video player has been detected and holds the update off until the video player closes or plays an another video file after the 3 30 seconds intervals.

**Comment by po5** [comment]
An attempt was made in 965f13c.

Running the script with files already playing may initially show previously opened files with some players, resulting in something like:
```
Queuing Aria The Animation - Episode 04.mkv for list update
Queuing Aria The Animation - Episode 06.mkv for list update
Queuing Aria The Animation - Episode 03.mkv for list update
```

That's because these files are still opened by the player, could be fixed by doing guessit stuff earlier but it's only a debug output anyway.

**Comment by CypherNL** [comment]
Thanks! I've got no more request regarding this feature. I will close this one.
